[build]
  command = "npm run build"  # Command to build your project
  publish = "build"          # Directory to deploy (output directory after build)

[[redirects]] 
  from = "/*"
  to = "/index.html"
  status = 200
